[project]
name = "streamlit_app"
version = "1.0.0"
description = "Fish Audio TTS Streamlit App"
dependencies = []

[build-system]
requires = ["setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["streamlit_app"]

[tool.uv]
package = false
